// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwHQcl2fflNpnnTk2fzbl_jvDLwVK8MXY',
    appId: '1:773314628426:web:03c9cb1b6c6690f8ba0fb3',
    messagingSenderId: '773314628426',
    projectId: 'functions-test-7bc83',
    authDomain: 'functions-test-7bc83.firebaseapp.com',
    databaseURL: 'https://functions-test-7bc83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'functions-test-7bc83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVHKhR9uog9hUugBs9zTMzamQBOHe6dA',
    appId: '1:773314628426:android:c058112eef6cb6ccba0fb3',
    messagingSenderId: '773314628426',
    projectId: 'functions-test-7bc83',
    databaseURL: 'https://functions-test-7bc83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'functions-test-7bc83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtzgf9r2WC4E9H3YjnjX1AF9cuXmStFw4',
    appId: '1:773314628426:ios:88fbf0c7e5e7e16dba0fb3',
    messagingSenderId: '773314628426',
    projectId: 'functions-test-7bc83',
    databaseURL: 'https://functions-test-7bc83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'functions-test-7bc83.appspot.com',
    iosClientId: '773314628426-cusf3db3eeugenr3si5mukpgc0n5btv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWavysmapNative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtzgf9r2WC4E9H3YjnjX1AF9cuXmStFw4',
    appId: '1:773314628426:ios:88fbf0c7e5e7e16dba0fb3',
    messagingSenderId: '773314628426',
    projectId: 'functions-test-7bc83',
    databaseURL: 'https://functions-test-7bc83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'functions-test-7bc83.appspot.com',
    iosClientId: '773314628426-cusf3db3eeugenr3si5mukpgc0n5btv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWavysmapNative',
  );
}
